version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing Terraform...
      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - cd terraform
      - echo Initializing Terraform...
      - terraform init
      - echo Validating Terraform configuration...
      - terraform validate
      
  build:
    commands:
      - echo Build phase started on `date`
      - echo Running Terraform plan...
      - terraform plan -var="environment=$TF_VAR_environment" -var="project_name=$TF_VAR_project_name" -var="aws_region=$TF_VAR_aws_region" -out=tfplan
      - echo Showing plan details...
      - terraform show -no-color tfplan > plan-output.txt
      
  post_build:
    commands:
      - echo Post-build phase completed on `date`
      - echo Plan saved to tfplan file

artifacts:
  files:
    - 'terraform/tfplan'
    - 'terraform/plan-output.txt'
    - 'terraform/.terraform/**/*'
  name: terraform-plan-artifacts 